name: Debug

on:
  workflow_dispatch:
    inputs:
      clojureRepo:
        description: "Repository name with owner."
        required: true
        default: 'clojure/clojure'
      clojureRef:
        description: "The branch, tag or SHA to checkout"
        required: true
        default: 'master'

jobs:

  test-alphabase:
    uses: ./.github/workflows/deps-test.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      testCmd: '-M:test "$@"'
      testDir: '.'
      subjectRepo: 'greglook/alphabase'
      subjectRef: 'main'

  ## Uses bb to run tests unsure how to override clj version
#  test-clj-yaml:
#      uses: ./.github/workflows/deps-test.yml
#      with:
#        clojureRepo: ${{ inputs.clojureRepo }}
#        clojureRef: ${{ inputs.clojureRef }}
#        testCmd: '-M:test'
#        testDir: '.'
#        subjectRepo: 'clj-commons/clj-yaml'
#        subjectRef: 'master'
#        javaVersion: '["11", "17", "21"]'
  ## CI Failing in repo
#  test-durable-queue:
#      uses: ./.github/workflows/lein-test.yml
#      with:
#        clojureRepo: ${{ inputs.clojureRepo }}
#        clojureRef: ${{ inputs.clojureRef }}
#        subjectRepo: 'clj-commons/durable-queue'
#        subjectRef: 'master'
        ## Uses xvfb
#  test-seesaw:
#      uses: ./.github/workflows/lein-test.yml
#      with:
#        clojureRepo: ${{ inputs.clojureRepo }}
#        clojureRef: ${{ inputs.clojureRef }}
#        preTest: 'export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start'
#        testCmd: 'lein deps; lein javac; export DISPLAY=:99.0; ./lazytest.sh'
#        subjectRepo: 'clj-commons/seesaw'
#        subjectRef: 'master'

