name: Debug

on:
  workflow_dispatch:
    inputs:
      clojureRepo:
        description: "Repository name with owner."
        required: true
        default: 'clojure/clojure'
      clojureRef:
        description: "The branch, tag or SHA to checkout"
        required: true
        default: 'master'

jobs:
  test-debug:
    uses: ./.github/workflows/test-deps-repo.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'scicloj/metamorph.ml'
      subjectRef: 'main'
      testDir: '.'
      testCmd: '-A:test -m kaocha.runner'