name: Debug

on:
  workflow_dispatch:
    inputs:
      clojureRepo:
        description: "Repository name with owner."
        required: true
        default: 'clojure/clojure'
      clojureRef:
        description: "The branch, tag or SHA to checkout"
        required: true
        default: 'master'

jobs:
  test-xtdb:
    uses: ./.github/workflows/test-lein-repo.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'xtdb/xtdb'
      subjectRef: '1.x'