name: Test Against Contrib and Nu

on:
  workflow_dispatch:
    inputs:
      clojureRepo:
        description: "Repository name with owner."
        required: true
        default: 'clojure/clojure'
      clojureRef:
        description: "The branch, tag or SHA to checkout"
        required: true
        default: 'master'

jobs:
  test-core-cache:
    uses: ./.github/workflows/test-mvn-repo.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'clojure/core.cache'
      subjectRef: 'master'

  test-core-logic:
    uses: ./.github/workflows/test-mvn-repo.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'clojure/core.logic'
      subjectRef: 'master'

  test-core-match:
    uses: ./.github/workflows/test-mvn-repo.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'clojure/core.match'
      subjectRef: 'master'

  test-core-memoize:
    uses: ./.github/workflows/test-mvn-repo.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'clojure/core.memoize'
      subjectRef: 'master'

  test-math-combinatorics:
    uses: ./.github/workflows/test-mvn-repo.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'clojure/math.combinatorics'
      subjectRef: 'master'

  test-java-jdbc:
    uses: ./.github/workflows/test-mvn-repo.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'clojure/java.jdbc'
      subjectRef: 'master'

  test-data-json:
    uses: ./.github/workflows/test-mvn-repo.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'clojure/data.json'
      subjectRef: 'master'

  test-data-fressian:
    uses: ./.github/workflows/test-mvn-repo.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'clojure/data.fressian'
      subjectRef: 'master'

  test-data-csv:
    uses: ./.github/workflows/test-mvn-repo.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'clojure/data.csv'
      subjectRef: 'master'

  test-state-flow:
    uses: ./.github/workflows/test-lein-repo.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'nubank/state-flow'
      subjectRef: 'master'

  test-clojure-lsp:
    uses: ./.github/workflows/test-deps-repo.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'clojure-lsp/clojure-lsp'
      subjectRef: 'master'
      testDir: './lib'
      testCmd: '-M:test'