name: Test New Things

on:
  workflow_dispatch:
    inputs:
      clojureRepo:
        description: "Repository name with owner."
        required: true
        default: 'clojure/clojure'
      clojureRef:
        description: "The branch, tag or SHA to checkout"
        required: true
        default: 'master'

jobs:
  test-pedestal:
    uses: ./.github/workflows/deps-test.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'pedestal/pedestal'
      subjectRef: 'master'
      testDir: './tests'
      testCmd: '-X:test'



  test-fressian:
    uses: ./.github/workflows/mvn-test.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'Datomic/fressian'
      subjectRef: 'master'

  test-slingshot:
    uses: ./.github/workflows/lein-test.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'scgilardi/slingshot'
      subjectRef: 'master'

  test-clj-commons-iapetos:
    uses: ./.github/workflows/lein-test.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'clj-commons/iapetos'
      subjectRef: 'master'

  test-clj-commons-manifold:
    uses: ./.github/workflows/lein-test.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'clj-commons/manifold'
      subjectRef: 'master'

  test-cloffeine:
    uses: ./.github/workflows/lein-test.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'willcohen/cloffeine'
      subjectRef: 'master'

  test-pandect:
    uses: ./.github/workflows/lein-test.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'xsc/pandect'
      subjectRef: 'master'

  test-clj-jwt:
    uses: ./.github/workflows/lein-test.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'liquidz/clj-jwt'
      subjectRef: 'master'

  test-potemkin:
    uses: ./.github/workflows/lein-test.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'clj-commons/potemkin'
      subjectRef: 'master'


  test-ring-core:
    uses: ./.github/workflows/lein-test.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'ring-clojure/ring'
      subjectRef: 'master'

  test-carmine:
    uses: ./.github/workflows/lein-test.yml
    with:
      clojureRepo: ${{ inputs.clojureRepo }}
      clojureRef: ${{ inputs.clojureRef }}
      subjectRepo: 'taoensso/carmine'
      subjectRef: 'master'
